import { normalizeProtocol } from "../normalizeProtocol.js";

const rawConjuntivoFrouxoDensoV1 = {
  id: "conjuntivo-frouxo-denso-v1",
  name: "Especializações do Tecido Conjuntivo",
  domain: "histologia",
  description:
    "Investigação de especializações do tecido conjuntivo com base em matriz, fibras, tipos celulares e organização histológica.",
  observations: [
    {
      structure: "fibras_extracelulares",
      label: "Fibras extracelulares",
      negativeWeightFactor: 0.85,
      values: [
        "discretas",
        "colagenas_abundantes",
        "elasticas_abundantes",
        "inconspicuas",
        "mineralizadas",
      ],
    },
    {
      structure: "organizacao_matriz",
      label: "Organização da matriz",
      negativeWeightFactor: 0.8,
      values: [
        "frouxa",
        "feixes_espessos",
        "homogenea",
        "lamelas_concentricas",
        "trabeculas",
        "lobular",
        "cordoes_celulares",
      ],
    },
    {
      structure: "substancia_fundamental",
      label: "Substância fundamental",
      negativeWeightFactor: 0.8,
      values: [
        "abundante",
        "escassa",
        "gelatinosa",
        "mineralizada",
        "lipidica",
      ],
    },
    {
      structure: "celularidade",
      label: "Celularidade",
      negativeWeightFactor: 0.75,
      values: [
        "alta",
        "moderada",
        "baixa",
      ],
    },
    {
      structure: "vascularizacao",
      label: "Vascularização",
      negativeWeightFactor: 0.75,
      values: [
        "evidente",
        "discreta",
        "ausente",
      ],
    },
    {
      structure: "tipo_celular_predominante",
      label: "Tipo celular predominante",
      negativeWeightFactor: 0.8,
      values: [
        "fibroblastos",
        "condrocitos",
        "osteocitos",
        "adipocitos",
        "celulas_hematopoieticas",
      ],
    },
    {
      structure: "cavidades_matriz",
      label: "Cavidades na matriz",
      negativeWeightFactor: 0.8,
      values: [
        "ausentes",
        "lacunas_condrocitarias",
        "osteoplastos",
      ],
    },
    {
      structure: "pericondrio",
      label: "Pericôndrio",
      negativeWeightFactor: 0.75,
      values: [
        "presente",
        "ausente",
      ],
    },
  ],
  hypotheses: [
    {
      id: "conjuntivo_frouxo",
      name: "Conjuntivo frouxo",
      level: "subtipo",
      clue:
        "Matriz frouxa, substância fundamental abundante e fibroblastos em tecido vascularizado favorecem conjuntivo frouxo.",
    },
    {
      id: "conjuntivo_denso",
      name: "Conjuntivo denso",
      level: "subtipo",
      clue:
        "Feixes colágenos espessos, pouca substância fundamental e baixa celularidade favorecem conjuntivo denso.",
    },
    {
      id: "cartilagem_hialina",
      name: "Cartilagem hialina",
      level: "subtipo",
      clue:
        "Matriz homogênea, condrócitos em lacunas, pericôndrio e ausência de vascularização sustentam cartilagem hialina.",
    },
    {
      id: "cartilagem_elastica",
      name: "Cartilagem elástica",
      level: "subtipo",
      clue:
        "Condrócitos em lacunas associados a fibras elásticas abundantes favorecem cartilagem elástica.",
    },
    {
      id: "tecido_osseo_compacto",
      name: "Tecido ósseo compacto",
      level: "subtipo",
      clue:
        "Lamelas concêntricas, matriz mineralizada e osteócitos em osteoplastos fortalecem tecido ósseo compacto.",
    },
    {
      id: "tecido_osseo_esponjoso",
      name: "Tecido ósseo esponjoso",
      level: "subtipo",
      clue:
        "Trabéculas ósseas, matriz mineralizada e osteócitos em osteoplastos favorecem tecido ósseo esponjoso.",
    },
    {
      id: "fibrocartilagem",
      name: "Fibrocartilagem",
      level: "subtipo",
      clue:
        "Feixes colágenos espessos associados a condrócitos em lacunas, sem pericôndrio, favorecem fibrocartilagem.",
    },
    {
      id: "tecido_adiposo",
      name: "Tecido adiposo",
      level: "subtipo",
      clue:
        "Arranjo lobular, adipócitos e vascularização evidente fortalecem a hipótese de tecido adiposo.",
    },
    {
      id: "tecido_hematopoietico",
      name: "Tecido hematopoietico",
      level: "subtipo",
      clue:
        "Cordões celulares, alta celularidade, vascularização evidente e predomínio de células hematopoieticas favorecem esse tecido.",
    },
  ],
  rules: [
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "fibras_extracelulares",
      value: "discretas",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "organizacao_matriz",
      value: "frouxa",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "substancia_fundamental",
      value: "abundante",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "celularidade",
      value: "moderada",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "vascularizacao",
      value: "evidente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "tipo_celular_predominante",
      value: "fibroblastos",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "cavidades_matriz",
      value: "ausentes",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "fibras_extracelulares",
      value: "colagenas_abundantes",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "organizacao_matriz",
      value: "feixes_espessos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "substancia_fundamental",
      value: "escassa",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "celularidade",
      value: "baixa",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "vascularizacao",
      value: "discreta",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "tipo_celular_predominante",
      value: "fibroblastos",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "cavidades_matriz",
      value: "ausentes",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "fibras_extracelulares",
      value: "inconspicuas",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "organizacao_matriz",
      value: "homogenea",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "substancia_fundamental",
      value: "gelatinosa",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "celularidade",
      value: "moderada",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "vascularizacao",
      value: "ausente",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "cavidades_matriz",
      value: "lacunas_condrocitarias",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "pericondrio",
      value: "presente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "fibras_extracelulares",
      value: "elasticas_abundantes",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "organizacao_matriz",
      value: "homogenea",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "substancia_fundamental",
      value: "gelatinosa",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "celularidade",
      value: "moderada",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "vascularizacao",
      value: "ausente",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "cavidades_matriz",
      value: "lacunas_condrocitarias",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "pericondrio",
      value: "presente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "fibras_extracelulares",
      value: "mineralizadas",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "organizacao_matriz",
      value: "lamelas_concentricas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "substancia_fundamental",
      value: "mineralizada",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "celularidade",
      value: "baixa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "vascularizacao",
      value: "evidente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "cavidades_matriz",
      value: "osteoplastos",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "fibras_extracelulares",
      value: "mineralizadas",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "organizacao_matriz",
      value: "trabeculas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "substancia_fundamental",
      value: "mineralizada",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "celularidade",
      value: "moderada",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "vascularizacao",
      value: "evidente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "cavidades_matriz",
      value: "osteoplastos",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "fibras_extracelulares",
      value: "colagenas_abundantes",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "organizacao_matriz",
      value: "feixes_espessos",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "substancia_fundamental",
      value: "gelatinosa",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "celularidade",
      value: "baixa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "vascularizacao",
      value: "ausente",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "cavidades_matriz",
      value: "lacunas_condrocitarias",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "fibras_extracelulares",
      value: "inconspicuas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "organizacao_matriz",
      value: "lobular",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "substancia_fundamental",
      value: "lipidica",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "celularidade",
      value: "baixa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "vascularizacao",
      value: "evidente",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "tipo_celular_predominante",
      value: "adipocitos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "cavidades_matriz",
      value: "ausentes",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "fibras_extracelulares",
      value: "inconspicuas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "organizacao_matriz",
      value: "cordoes_celulares",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "substancia_fundamental",
      value: "escassa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "celularidade",
      value: "alta",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "vascularizacao",
      value: "evidente",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "tipo_celular_predominante",
      value: "celulas_hematopoieticas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "cavidades_matriz",
      value: "ausentes",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "pericondrio",
      value: "ausente",
      effect: "positive",
      weight: 1,
    },

    {
      hypothesis: "conjuntivo_frouxo",
      structure: "organizacao_matriz",
      value: "feixes_espessos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "substancia_fundamental",
      value: "escassa",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_frouxo",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "organizacao_matriz",
      value: "frouxa",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "substancia_fundamental",
      value: "abundante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "conjuntivo_denso",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "fibras_extracelulares",
      value: "elasticas_abundantes",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "organizacao_matriz",
      value: "lamelas_concentricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "cartilagem_hialina",
      structure: "vascularizacao",
      value: "evidente",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "fibras_extracelulares",
      value: "inconspicuas",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "organizacao_matriz",
      value: "lamelas_concentricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "cartilagem_elastica",
      structure: "vascularizacao",
      value: "evidente",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "cavidades_matriz",
      value: "lacunas_condrocitarias",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_osseo_compacto",
      structure: "pericondrio",
      value: "presente",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "organizacao_matriz",
      value: "lamelas_concentricas",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_osseo_esponjoso",
      structure: "pericondrio",
      value: "presente",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "fibras_extracelulares",
      value: "elasticas_abundantes",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "organizacao_matriz",
      value: "homogenea",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "fibrocartilagem",
      structure: "pericondrio",
      value: "presente",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "organizacao_matriz",
      value: "feixes_espessos",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "tipo_celular_predominante",
      value: "fibroblastos",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "tipo_celular_predominante",
      value: "condrocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_adiposo",
      structure: "tipo_celular_predominante",
      value: "osteocitos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "organizacao_matriz",
      value: "lamelas_concentricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "cavidades_matriz",
      value: "osteoplastos",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "tecido_hematopoietico",
      structure: "pericondrio",
      value: "presente",
      effect: "negative",
      weight: 2,
    },
  ],
};

export const conjuntivoFrouxoDensoV1 =
  normalizeProtocol(
    rawConjuntivoFrouxoDensoV1
  );
