import { normalizeProtocol } from "../normalizeProtocol.js";

const rawOrgaosHistologicosV1 = {
  id: "orgaos-histologicos-v1",
  name: "Órgãos Histológicos",
  domain: "histologia",
  description:
    "Investigação de órgãos com base na combinação entre tecidos e estruturas morfológicas observáveis na lâmina.",
  observations: [
    {
      structure: "epitelio_revestimento",
      label: "Epitélio de revestimento",
      negativeWeightFactor: 0.85,
      values: [
        "simples_pavimentoso",
        "simples_cilindrico",
        "simples_cubico",
        "pseudoestratificado_ciliado",
        "estratificado_pavimentoso",
        "transicional",
        "germinativo_estratificado",
        "pseudoestratificado_com_estereocilios",
        "simples_cubico_ou_cilindrico",
        "cilindrico_pseudoestratificado_pregueado",
        "endotelio",
        "ausente_ou_nao_aplicavel",
      ],
    },
    {
      structure: "conjuntivo_predominante",
      label: "Conjuntivo predominante",
      negativeWeightFactor: 0.8,
      values: [
        "frouxo",
        "denso",
        "misto",
      ],
    },
    {
      structure: "musculo_predominante",
      label: "Músculo predominante",
      negativeWeightFactor: 0.8,
      values: [
        "liso",
        "estriado",
        "ausente_ou_discreto",
      ],
    },
    {
      structure: "estrutura_marcante",
      label: "Estrutura marcante",
      negativeWeightFactor: 0.85,
      values: [
        "vilosidades",
        "cartilagem",
        "anexos_cutaneos",
        "papilas",
        "glandulas_gastricas",
        "sem_especializacao_dominante",
        "tubulos_seminiferos",
        "estereocilios",
        "glandulas_tubuloalveolares",
        "pregas_mucosas_complexas",
        "alveolos",
        "glomerulos",
        "pregas_uroteliais",
        "cordoes_hepaticos",
        "discos_intercalares",
        "foliculos_tireoidianos",
        "acinos_serosos_e_ilhotas",
        "foliculos_linfoides",
        "polpa_branca_e_vermelha",
      ],
    },
    {
      structure: "organizacao_geral",
      label: "Organização geral",
      negativeWeightFactor: 0.8,
      values: [
        "mucosa_submucosa_tunica_muscular",
        "epiderme_derme",
        "feixes_musculares_entrelacados",
        "lobulos_com_tubulos",
        "ducto_enovelado",
        "acinos_em_estroma_fibromuscular",
        "mucosa_pregueada",
        "parenquima_alveolar",
        "cortex_medula",
        "mucosa_distensivel",
        "lobulos_hepaticos",
        "miocardio",
        "foliculos_com_coloide",
        "lobulos_acinares",
        "cortex_medula_linfoide",
        "trabeculas_esplenicas",
      ],
    },
    {
      structure: "superficie_ou_luz",
      label: "Superfície ou luz",
      negativeWeightFactor: 0.75,
      values: [
        "superficie_externa",
        "luz_tubular",
        "sem_luz_predominante",
        "espacos_aereos",
        "luz_com_espermatozoides",
        "luz_com_secrecao",
        "luz_urinaria",
      ],
    },
    {
      structure: "conteudo_luminal",
      label: "Conteúdo luminal",
      negativeWeightFactor: 0.75,
      values: [
        "espermatozoides",
        "secrecao_eosinofilica",
        "corpora_amylacea",
        "ausente_ou_inexpressivo",
        "urina",
        "sangue_em_sinusoides",
        "sangue_em_camaras",
        "coloide",
        "linfocitos",
      ],
    },
  ],
  hypotheses: [
    {
      id: "pele",
      name: "Pele",
      level: "orgao",
      clue:
        "Epitélio estratificado pavimentoso, derme conjuntiva densa e anexos cutâneos fortalecem essa hipótese.",
    },
    {
      id: "traqueia",
      name: "Traqueia",
      level: "orgao",
      clue:
        "Epitélio pseudoestratificado ciliado, cartilagem e organização tubular favorecem traqueia.",
    },
    {
      id: "intestino_delgado",
      name: "Intestino delgado",
      level: "orgao",
      clue:
        "Epitélio simples cilíndrico, vilosidades e túnica muscular lisa sustentam intestino delgado.",
    },
    {
      id: "lingua",
      name: "Língua",
      level: "orgao",
      clue:
        "Papilas associadas a feixes de músculo estriado sem luz predominante fortalecem a hipótese de língua.",
    },
    {
      id: "esofago",
      name: "Esôfago",
      level: "orgao",
      clue:
        "Epitélio estratificado pavimentoso, organização tubular e ausência de estrutura marcante dominante favorecem esôfago.",
    },
    {
      id: "estomago",
      name: "Estômago",
      level: "orgao",
      clue:
        "Epitélio simples cilíndrico, glândulas gástricas e túnica muscular lisa fortalecem a hipótese de estômago.",
    },
    {
      id: "testiculo",
      name: "Testículo",
      level: "orgao",
      clue:
        "Túbulos seminíferos, epitélio germinativo estratificado e arranjo lobular tubular favorecem testículo.",
    },
    {
      id: "epididimo",
      name: "Epidídimo",
      level: "orgao",
      clue:
        "Ducto enovelado com epitélio pseudoestratificado com estereocílios e luz com espermatozoides fortalecem epidídimo.",
    },
    {
      id: "prostata",
      name: "Próstata",
      level: "orgao",
      clue:
        "Glândulas túbulo-alveolares em estroma fibromuscular com corpora amylacea favorecem próstata.",
    },
    {
      id: "vesicula_seminal",
      name: "Vesícula seminal",
      level: "orgao",
      clue:
        "Mucosa muito pregueada, luz com secreção e epitélio cilíndrico pregueado fortalecem vesícula seminal.",
    },
    {
      id: "pulmao",
      name: "Pulmão",
      level: "orgao",
      clue:
        "Alvéolos, parênquima alveolar e espaços aéreos amplos favorecem pulmão.",
    },
    {
      id: "rim",
      name: "Rim",
      level: "orgao",
      clue:
        "Glomérulos, organização em córtex e medula e túbulos com epitélio simples cúbico fortalecem rim.",
    },
    {
      id: "bexiga",
      name: "Bexiga",
      level: "orgao",
      clue:
        "Urotélio, mucosa distensível e pregas uroteliais associadas a luz urinária favorecem bexiga.",
    },
    {
      id: "figado",
      name: "Fígado",
      level: "orgao",
      clue:
        "Cordões hepáticos, arranjo lobular e sinusoides com sangue favorecem fígado.",
    },
    {
      id: "coracao",
      name: "Coração",
      level: "orgao",
      clue:
        "Miocárdio, músculo estriado cardíaco, endotélio e discos intercalares favorecem coração.",
    },
    {
      id: "tireoide",
      name: "Tireoide",
      level: "orgao",
      clue:
        "Folículos tireoidianos revestidos por epitélio simples cúbico e preenchidos por coloide sustentam tireoide.",
    },
    {
      id: "pancreas",
      name: "Pâncreas",
      level: "orgao",
      clue:
        "Lóbulos acinares, ácinos serosos e ilhotas endócrinas favorecem pâncreas.",
    },
    {
      id: "linfonodo",
      name: "Linfonodo",
      level: "orgao",
      clue:
        "Córtex e medula linfoide com folículos linfoides e muitos linfócitos fortalecem linfonodo.",
    },
    {
      id: "baco",
      name: "Baço",
      level: "orgao",
      clue:
        "Polpa branca e vermelha, trabéculas esplênicas e sangue em sinusoides favorecem baço.",
    },
  ],
  rules: [
    {
      hypothesis: "pulmao",
      structure: "epitelio_revestimento",
      value: "simples_pavimentoso",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "pulmao",
      structure: "conjuntivo_predominante",
      value: "frouxo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "pulmao",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "pulmao",
      structure: "estrutura_marcante",
      value: "alveolos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pulmao",
      structure: "organizacao_geral",
      value: "parenquima_alveolar",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pulmao",
      structure: "superficie_ou_luz",
      value: "espacos_aereos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pulmao",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "rim",
      structure: "epitelio_revestimento",
      value: "simples_cubico",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "rim",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "rim",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "rim",
      structure: "estrutura_marcante",
      value: "glomerulos",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "rim",
      structure: "organizacao_geral",
      value: "cortex_medula",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "rim",
      structure: "superficie_ou_luz",
      value: "luz_urinaria",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "rim",
      structure: "conteudo_luminal",
      value: "urina",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "bexiga",
      structure: "epitelio_revestimento",
      value: "transicional",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "bexiga",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "bexiga",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "bexiga",
      structure: "estrutura_marcante",
      value: "pregas_uroteliais",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "bexiga",
      structure: "organizacao_geral",
      value: "mucosa_distensivel",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "bexiga",
      structure: "superficie_ou_luz",
      value: "luz_urinaria",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "bexiga",
      structure: "conteudo_luminal",
      value: "urina",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "figado",
      structure: "epitelio_revestimento",
      value: "simples_cubico_ou_cilindrico",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "figado",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "figado",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "figado",
      structure: "estrutura_marcante",
      value: "cordoes_hepaticos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "figado",
      structure: "organizacao_geral",
      value: "lobulos_hepaticos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "figado",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "figado",
      structure: "conteudo_luminal",
      value: "sangue_em_sinusoides",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "coracao",
      structure: "epitelio_revestimento",
      value: "endotelio",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "coracao",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "coracao",
      structure: "musculo_predominante",
      value: "estriado",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "coracao",
      structure: "estrutura_marcante",
      value: "discos_intercalares",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "coracao",
      structure: "organizacao_geral",
      value: "miocardio",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "coracao",
      structure: "conteudo_luminal",
      value: "sangue_em_camaras",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "tireoide",
      structure: "epitelio_revestimento",
      value: "simples_cubico",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "tireoide",
      structure: "conjuntivo_predominante",
      value: "frouxo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tireoide",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "tireoide",
      structure: "estrutura_marcante",
      value: "foliculos_tireoidianos",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "tireoide",
      structure: "organizacao_geral",
      value: "foliculos_com_coloide",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "tireoide",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "tireoide",
      structure: "conteudo_luminal",
      value: "coloide",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pancreas",
      structure: "epitelio_revestimento",
      value: "simples_cubico_ou_cilindrico",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "pancreas",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "pancreas",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "pancreas",
      structure: "estrutura_marcante",
      value: "acinos_serosos_e_ilhotas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "pancreas",
      structure: "organizacao_geral",
      value: "lobulos_acinares",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "pancreas",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "pancreas",
      structure: "conteudo_luminal",
      value: "secrecao_eosinofilica",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "linfonodo",
      structure: "epitelio_revestimento",
      value: "ausente_ou_nao_aplicavel",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "linfonodo",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "linfonodo",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "linfonodo",
      structure: "estrutura_marcante",
      value: "foliculos_linfoides",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "linfonodo",
      structure: "organizacao_geral",
      value: "cortex_medula_linfoide",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "linfonodo",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "linfonodo",
      structure: "conteudo_luminal",
      value: "linfocitos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "baco",
      structure: "epitelio_revestimento",
      value: "ausente_ou_nao_aplicavel",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "baco",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "baco",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "baco",
      structure: "estrutura_marcante",
      value: "polpa_branca_e_vermelha",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "baco",
      structure: "organizacao_geral",
      value: "trabeculas_esplenicas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "baco",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "baco",
      structure: "conteudo_luminal",
      value: "sangue_em_sinusoides",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pele",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "pele",
      structure: "conjuntivo_predominante",
      value: "denso",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "pele",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "pele",
      structure: "estrutura_marcante",
      value: "anexos_cutaneos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pele",
      structure: "organizacao_geral",
      value: "epiderme_derme",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "pele",
      structure: "superficie_ou_luz",
      value: "superficie_externa",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "pele",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "traqueia",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "traqueia",
      structure: "conjuntivo_predominante",
      value: "frouxo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "traqueia",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "traqueia",
      structure: "organizacao_geral",
      value: "mucosa_submucosa_tunica_muscular",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "traqueia",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "traqueia",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "epitelio_revestimento",
      value: "simples_cilindrico",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "conjuntivo_predominante",
      value: "frouxo",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "organizacao_geral",
      value: "mucosa_submucosa_tunica_muscular",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "lingua",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "lingua",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "lingua",
      structure: "musculo_predominante",
      value: "estriado",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "lingua",
      structure: "estrutura_marcante",
      value: "papilas",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "lingua",
      structure: "organizacao_geral",
      value: "feixes_musculares_entrelacados",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "lingua",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "lingua",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "esofago",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "esofago",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "esofago",
      structure: "estrutura_marcante",
      value: "sem_especializacao_dominante",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "esofago",
      structure: "organizacao_geral",
      value: "mucosa_submucosa_tunica_muscular",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "esofago",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "esofago",
      structure: "conteudo_luminal",
      value: "ausente_ou_inexpressivo",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "estomago",
      structure: "epitelio_revestimento",
      value: "simples_cilindrico",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "estomago",
      structure: "conjuntivo_predominante",
      value: "frouxo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "estomago",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "estomago",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "estomago",
      structure: "organizacao_geral",
      value: "mucosa_submucosa_tunica_muscular",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "estomago",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "estomago",
      structure: "conteudo_luminal",
      value: "secrecao_eosinofilica",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "testiculo",
      structure: "epitelio_revestimento",
      value: "germinativo_estratificado",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "testiculo",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "testiculo",
      structure: "musculo_predominante",
      value: "ausente_ou_discreto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "testiculo",
      structure: "estrutura_marcante",
      value: "tubulos_seminiferos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "testiculo",
      structure: "organizacao_geral",
      value: "lobulos_com_tubulos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "testiculo",
      structure: "superficie_ou_luz",
      value: "luz_com_espermatozoides",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "testiculo",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_com_estereocilios",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "epididimo",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "epididimo",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "estrutura_marcante",
      value: "estereocilios",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "epididimo",
      structure: "organizacao_geral",
      value: "ducto_enovelado",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "epididimo",
      structure: "superficie_ou_luz",
      value: "luz_com_espermatozoides",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "epididimo",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "prostata",
      structure: "epitelio_revestimento",
      value: "simples_cubico_ou_cilindrico",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "prostata",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "estrutura_marcante",
      value: "glandulas_tubuloalveolares",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "prostata",
      structure: "organizacao_geral",
      value: "acinos_em_estroma_fibromuscular",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "prostata",
      structure: "superficie_ou_luz",
      value: "luz_com_secrecao",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "epitelio_revestimento",
      value: "cilindrico_pseudoestratificado_pregueado",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "conjuntivo_predominante",
      value: "misto",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "musculo_predominante",
      value: "liso",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "estrutura_marcante",
      value: "pregas_mucosas_complexas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "organizacao_geral",
      value: "mucosa_pregueada",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "superficie_ou_luz",
      value: "luz_com_secrecao",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "conteudo_luminal",
      value: "secrecao_eosinofilica",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "pele",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pele",
      structure: "musculo_predominante",
      value: "estriado",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "pele",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pele",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pele",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pele",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "pele",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "traqueia",
      structure: "epitelio_revestimento",
      value: "simples_cilindrico",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "traqueia",
      structure: "estrutura_marcante",
      value: "papilas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "traqueia",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "traqueia",
      structure: "estrutura_marcante",
      value: "sem_especializacao_dominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "musculo_predominante",
      value: "estriado",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "traqueia",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "estrutura_marcante",
      value: "sem_especializacao_dominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "musculo_predominante",
      value: "estriado",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "intestino_delgado",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "lingua",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "lingua",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "lingua",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "lingua",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "lingua",
      structure: "musculo_predominante",
      value: "liso",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "lingua",
      structure: "superficie_ou_luz",
      value: "luz_tubular",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "lingua",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "epitelio_revestimento",
      value: "simples_cilindrico",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "esofago",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "estrutura_marcante",
      value: "papilas",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "esofago",
      structure: "estrutura_marcante",
      value: "glandulas_gastricas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "superficie_ou_luz",
      value: "superficie_externa",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "esofago",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "esofago",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_ciliado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "epitelio_revestimento",
      value: "estratificado_pavimentoso",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "estomago",
      structure: "estrutura_marcante",
      value: "vilosidades",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "estomago",
      structure: "estrutura_marcante",
      value: "cartilagem",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "estrutura_marcante",
      value: "papilas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "estrutura_marcante",
      value: "sem_especializacao_dominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "estomago",
      structure: "superficie_ou_luz",
      value: "superficie_externa",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "estomago",
      structure: "superficie_ou_luz",
      value: "sem_luz_predominante",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "estomago",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "testiculo",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_com_estereocilios",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "testiculo",
      structure: "estrutura_marcante",
      value: "estereocilios",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "testiculo",
      structure: "estrutura_marcante",
      value: "glandulas_tubuloalveolares",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "testiculo",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "epitelio_revestimento",
      value: "germinativo_estratificado",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "estrutura_marcante",
      value: "tubulos_seminiferos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "estrutura_marcante",
      value: "glandulas_tubuloalveolares",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "epididimo",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_com_estereocilios",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "estrutura_marcante",
      value: "tubulos_seminiferos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "prostata",
      structure: "estrutura_marcante",
      value: "pregas_mucosas_complexas",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "prostata",
      structure: "conteudo_luminal",
      value: "espermatozoides",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "epitelio_revestimento",
      value: "pseudoestratificado_com_estereocilios",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "estrutura_marcante",
      value: "glandulas_tubuloalveolares",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "estrutura_marcante",
      value: "tubulos_seminiferos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "vesicula_seminal",
      structure: "conteudo_luminal",
      value: "corpora_amylacea",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pulmao",
      structure: "estrutura_marcante",
      value: "glomerulos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pulmao",
      structure: "estrutura_marcante",
      value: "tubulos_seminiferos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "pulmao",
      structure: "superficie_ou_luz",
      value: "luz_urinaria",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "rim",
      structure: "epitelio_revestimento",
      value: "transicional",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "rim",
      structure: "estrutura_marcante",
      value: "alveolos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "rim",
      structure: "estrutura_marcante",
      value: "pregas_uroteliais",
      effect: "negative",
      weight: 2,
    },
    {
      hypothesis: "bexiga",
      structure: "epitelio_revestimento",
      value: "simples_cubico",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "bexiga",
      structure: "estrutura_marcante",
      value: "glomerulos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "bexiga",
      structure: "conteudo_luminal",
      value: "sangue_em_sinusoides",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "figado",
      structure: "estrutura_marcante",
      value: "alveolos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "figado",
      structure: "estrutura_marcante",
      value: "glomerulos",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "figado",
      structure: "superficie_ou_luz",
      value: "luz_urinaria",
      effect: "negative",
      weight: 3,
    },
  ],
};

export const orgaosHistologicosV1 =
  normalizeProtocol(
    rawOrgaosHistologicosV1
  );
