import { normalizeProtocol } from "../normalizeProtocol.js";

const rawFamiliasAngiospermasBrasilV1 = {
  id: "familias-angiospermas-brasil-v1",
  name: "Famílias Selecionadas de Angiospermas",
  domain: "botanica",
  description:
    "Investigação de famílias importantes de angiospermas com grande representatividade no Brasil, baseada em porte, folhas, flores, androceu, ovário e fruto.",
  observations: [
    {
      structure: "porte",
      label: "Porte predominante",
      negativeWeightFactor: 0.75,
      values: [
        "graminoide",
        "lenhoso",
        "herbaceo_arbustivo",
        "aromatico",
      ],
    },
    {
      structure: "folhas",
      label: "Folhas",
      negativeWeightFactor: 0.8,
      values: [
        "bainha_aberta_paralela",
        "tristicas_bainha_fechada",
        "compostas_com_pulvino",
        "opostas_com_glandulas",
        "opostas_acrodromas",
        "opostas_decussadas",
        "alternas_ou_pares_desiguais",
        "roseta_ou_variavel",
      ],
    },
    {
      structure: "flor",
      label: "Flor",
      negativeWeightFactor: 0.8,
      values: [
        "reduzida_ou_inconspicua",
        "papilionacea",
        "actinomorfa_com_hipanto",
        "bilabiada",
        "pentamera_gamopetala",
        "em_capitulo",
      ],
    },
    {
      structure: "destaque_reprodutivo",
      label: "Destaque reprodutivo",
      negativeWeightFactor: 0.85,
      values: [
        "espiguetas",
        "diadelfos_ou_livres",
        "muitos_estames",
        "anteras_por_poros",
        "estames_didinamos",
        "estames_epipetalos",
        "anteras_concrescidas",
      ],
    },
    {
      structure: "ovario",
      label: "Posição do ovário",
      negativeWeightFactor: 0.75,
      values: [
        "supero",
        "infero",
        "pouco_diagnostico",
      ],
    },
    {
      structure: "fruto",
      label: "Fruto",
      negativeWeightFactor: 0.8,
      values: [
        "cariopse",
        "aquenio",
        "legume",
        "baga_ou_capsula_infera",
        "capsula_ou_baga_com_calice_persistente",
        "esquizocarpico_4_nuculas",
        "cipsela_com_papo",
      ],
    },
  ],
  hypotheses: [
    {
      id: "poaceae",
      name: "Poaceae",
      level: "familia",
      clue:
        "Gramíneas com folhas paralelinérveas de bainha aberta, espiguetas e cariopse favorecem Poaceae.",
    },
    {
      id: "cyperaceae",
      name: "Cyperaceae",
      level: "familia",
      clue:
        "Aspecto graminoide com folhas trísticas, bainha fechada, espiguetas e aquênio favorece Cyperaceae.",
    },
    {
      id: "fabaceae",
      name: "Fabaceae",
      level: "familia",
      clue:
        "Folhas compostas com pulvinos, flor papilionácea e fruto legume sustentam Fabaceae.",
    },
    {
      id: "myrtaceae",
      name: "Myrtaceae",
      level: "familia",
      clue:
        "Plantas lenhosas com folhas opostas glandulosas, muitos estames e ovário ínfero favorecem Myrtaceae.",
    },
    {
      id: "melastomataceae",
      name: "Melastomataceae",
      level: "familia",
      clue:
        "Folhas opostas com nervação acródroma e anteras poricidas são sinais fortes de Melastomataceae.",
    },
    {
      id: "lamiaceae",
      name: "Lamiaceae",
      level: "familia",
      clue:
        "Folhas opostas decussadas, odor aromático, flor bilabiada e fruto em quatro núculas favorecem Lamiaceae.",
    },
    {
      id: "solanaceae",
      name: "Solanaceae",
      level: "familia",
      clue:
        "Folhas alternas, flor pentâmera gamopétala, estames epipétalos e frutos em baga ou cápsula favorecem Solanaceae.",
    },
    {
      id: "asteraceae",
      name: "Asteraceae",
      level: "familia",
      clue:
        "Capítulo, anteras concrescidas, ovário ínfero e cipsela com papo sustentam Asteraceae.",
    },
  ],
  rules: [
    {
      hypothesis: "poaceae",
      structure: "porte",
      value: "graminoide",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "poaceae",
      structure: "folhas",
      value: "bainha_aberta_paralela",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "poaceae",
      structure: "flor",
      value: "reduzida_ou_inconspicua",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "poaceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "poaceae",
      structure: "ovario",
      value: "pouco_diagnostico",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "poaceae",
      structure: "fruto",
      value: "cariopse",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "cyperaceae",
      structure: "porte",
      value: "graminoide",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "cyperaceae",
      structure: "folhas",
      value: "tristicas_bainha_fechada",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "cyperaceae",
      structure: "flor",
      value: "reduzida_ou_inconspicua",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "cyperaceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "cyperaceae",
      structure: "ovario",
      value: "pouco_diagnostico",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "cyperaceae",
      structure: "fruto",
      value: "aquenio",
      effect: "positive",
      weight: 6,
    },

    {
      hypothesis: "fabaceae",
      structure: "porte",
      value: "herbaceo_arbustivo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "fabaceae",
      structure: "folhas",
      value: "compostas_com_pulvino",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "fabaceae",
      structure: "flor",
      value: "papilionacea",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "fabaceae",
      structure: "destaque_reprodutivo",
      value: "diadelfos_ou_livres",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fabaceae",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "fabaceae",
      structure: "fruto",
      value: "legume",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "myrtaceae",
      structure: "porte",
      value: "lenhoso",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "myrtaceae",
      structure: "folhas",
      value: "opostas_com_glandulas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "myrtaceae",
      structure: "flor",
      value: "actinomorfa_com_hipanto",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "myrtaceae",
      structure: "destaque_reprodutivo",
      value: "muitos_estames",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "myrtaceae",
      structure: "ovario",
      value: "infero",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "myrtaceae",
      structure: "fruto",
      value: "baga_ou_capsula_infera",
      effect: "positive",
      weight: 5,
    },

    {
      hypothesis: "melastomataceae",
      structure: "porte",
      value: "herbaceo_arbustivo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "melastomataceae",
      structure: "folhas",
      value: "opostas_acrodromas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "melastomataceae",
      structure: "flor",
      value: "actinomorfa_com_hipanto",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "melastomataceae",
      structure: "destaque_reprodutivo",
      value: "anteras_por_poros",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "melastomataceae",
      structure: "ovario",
      value: "infero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "melastomataceae",
      structure: "fruto",
      value:
        "capsula_ou_baga_com_calice_persistente",
      effect: "positive",
      weight: 5,
    },

    {
      hypothesis: "lamiaceae",
      structure: "porte",
      value: "aromatico",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "lamiaceae",
      structure: "folhas",
      value: "opostas_decussadas",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "lamiaceae",
      structure: "flor",
      value: "bilabiada",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "lamiaceae",
      structure: "destaque_reprodutivo",
      value: "estames_didinamos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "lamiaceae",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "lamiaceae",
      structure: "fruto",
      value: "esquizocarpico_4_nuculas",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "solanaceae",
      structure: "porte",
      value: "herbaceo_arbustivo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "solanaceae",
      structure: "folhas",
      value: "alternas_ou_pares_desiguais",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "solanaceae",
      structure: "flor",
      value: "pentamera_gamopetala",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "solanaceae",
      structure: "destaque_reprodutivo",
      value: "estames_epipetalos",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "solanaceae",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "solanaceae",
      structure: "fruto",
      value:
        "capsula_ou_baga_com_calice_persistente",
      effect: "positive",
      weight: 4,
    },

    {
      hypothesis: "asteraceae",
      structure: "porte",
      value: "herbaceo_arbustivo",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "asteraceae",
      structure: "folhas",
      value: "roseta_ou_variavel",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "asteraceae",
      structure: "flor",
      value: "em_capitulo",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "asteraceae",
      structure: "destaque_reprodutivo",
      value: "anteras_concrescidas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "asteraceae",
      structure: "ovario",
      value: "infero",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "asteraceae",
      structure: "fruto",
      value: "cipsela_com_papo",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "poaceae",
      structure: "folhas",
      value: "tristicas_bainha_fechada",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poaceae",
      structure: "flor",
      value: "papilionacea",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poaceae",
      structure: "fruto",
      value: "legume",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poaceae",
      structure: "fruto",
      value: "cipsela_com_papo",
      effect: "negative",
      weight: 5,
    },

    {
      hypothesis: "cyperaceae",
      structure: "folhas",
      value: "bainha_aberta_paralela",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "cyperaceae",
      structure: "flor",
      value: "papilionacea",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "cyperaceae",
      structure: "fruto",
      value: "cariopse",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "cyperaceae",
      structure: "flor",
      value: "em_capitulo",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "fabaceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "fabaceae",
      structure: "flor",
      value: "em_capitulo",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "fabaceae",
      structure: "fruto",
      value: "cariopse",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "fabaceae",
      structure: "ovario",
      value: "infero",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "myrtaceae",
      structure: "folhas",
      value: "opostas_acrodromas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "myrtaceae",
      structure: "destaque_reprodutivo",
      value: "anteras_por_poros",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "myrtaceae",
      structure: "flor",
      value: "papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "myrtaceae",
      structure: "fruto",
      value: "legume",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "melastomataceae",
      structure: "folhas",
      value: "opostas_com_glandulas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "melastomataceae",
      structure: "destaque_reprodutivo",
      value: "muitos_estames",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "melastomataceae",
      structure: "flor",
      value: "papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "melastomataceae",
      structure: "fruto",
      value: "legume",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "lamiaceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiaceae",
      structure: "flor",
      value: "em_capitulo",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiaceae",
      structure: "ovario",
      value: "infero",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiaceae",
      structure: "fruto",
      value: "cariopse",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "solanaceae",
      structure: "flor",
      value: "bilabiada",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "solanaceae",
      structure: "destaque_reprodutivo",
      value: "anteras_concrescidas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "solanaceae",
      structure: "ovario",
      value: "infero",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "solanaceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "asteraceae",
      structure: "flor",
      value: "papilionacea",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "asteraceae",
      structure: "destaque_reprodutivo",
      value: "espiguetas",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "asteraceae",
      structure: "ovario",
      value: "supero",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "asteraceae",
      structure: "fruto",
      value: "legume",
      effect: "negative",
      weight: 5,
    },
  ],
};

export const familiasAngiospermasBrasilV1 =
  normalizeProtocol(
    rawFamiliasAngiospermasBrasilV1
  );
