import { normalizeProtocol } from "../normalizeProtocol.js";

const rawOrdensAngiospermasBrasilV1 = {
  id: "ordens-angiospermas-brasil-v1",
  name: "Ordens Selecionadas de Angiospermas",
  domain: "botanica",
  description:
    "Investigação de ordens relevantes de angiospermas com representantes importantes no Brasil, baseada em caracteres florais, inflorescências, folhas e frutos.",
  observations: [
    {
      structure: "arranjo_foliar",
      label: "Arranjo foliar",
      negativeWeightFactor: 0.75,
      values: [
        "alternas",
        "opostas",
        "basais_em_touceira",
      ],
    },
    {
      structure: "simetria_floral",
      label: "Simetria floral",
      negativeWeightFactor: 0.8,
      values: [
        "actinomorfa",
        "zigomorfa",
        "reduzida_ou_inconspicua",
      ],
    },
    {
      structure: "fusao_da_corola",
      label: "Fusão da corola",
      negativeWeightFactor: 0.8,
      values: [
        "gamopetala",
        "dialipetala",
        "ausente_ou_reduzida",
      ],
    },
    {
      structure: "estrutura_marcante",
      label: "Estrutura marcante",
      negativeWeightFactor: 0.85,
      values: [
        "espiguetas",
        "flor_papilionacea",
        "muitos_estames",
        "flor_bilabiada",
        "anteras_concrescidas",
        "flor_5_mera_sem_marca_forte",
      ],
    },
    {
      structure: "ovario",
      label: "Posição do ovário",
      negativeWeightFactor: 0.75,
      values: [
        "supero",
        "infero",
        "pouco_diagnostico",
      ],
    },
    {
      structure: "tipo_de_fruto",
      label: "Tipo de fruto",
      negativeWeightFactor: 0.75,
      values: [
        "cariopse",
        "legume",
        "capsula_ou_baga",
        "aquenio_com_papo",
        "capsula_lenhosa_ou_baga_inferior",
      ],
    },
  ],
  hypotheses: [
    {
      id: "poales",
      name: "Poales",
      level: "ordem",
      clue:
        "Espiguetas, flores reduzidas e fruto do tipo cariopse favorecem Poales.",
    },
    {
      id: "fabales",
      name: "Fabales",
      level: "ordem",
      clue:
        "Flor papilionácea e fruto do tipo legume são as pistas mais fortes para Fabales.",
    },
    {
      id: "myrtales",
      name: "Myrtales",
      level: "ordem",
      clue:
        "Flores actinomorfas com muitos estames, folhas opostas e frutos variados com ovário geralmente ínfero favorecem Myrtales.",
    },
    {
      id: "lamiales",
      name: "Lamiales",
      level: "ordem",
      clue:
        "Flor zigomorfa bilabiada com corola gamopétala e folhas opostas favorece Lamiales.",
    },
    {
      id: "solanales",
      name: "Solanales",
      level: "ordem",
      clue:
        "Flores pentâmeras com corola gamopétala, geralmente actinomorfas, e frutos em cápsula ou baga sustentam Solanales.",
    },
    {
      id: "asterales",
      name: "Asterales",
      level: "ordem",
      clue:
        "Capítulo, anteras concrescidas e aquênio com papo são os sinais mais fortes para Asterales.",
    },
  ],
  rules: [
    {
      hypothesis: "poales",
      structure: "arranjo_foliar",
      value: "basais_em_touceira",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "poales",
      structure: "simetria_floral",
      value: "reduzida_ou_inconspicua",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "poales",
      structure: "fusao_da_corola",
      value: "ausente_ou_reduzida",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "poales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "poales",
      structure: "ovario",
      value: "pouco_diagnostico",
      effect: "positive",
      weight: 1,
    },
    {
      hypothesis: "poales",
      structure: "tipo_de_fruto",
      value: "cariopse",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "fabales",
      structure: "arranjo_foliar",
      value: "alternas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "fabales",
      structure: "simetria_floral",
      value: "zigomorfa",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fabales",
      structure: "fusao_da_corola",
      value: "dialipetala",
      effect: "positive",
      weight: 4,
    },
    {
      hypothesis: "fabales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "fabales",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "fabales",
      structure: "tipo_de_fruto",
      value: "legume",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "myrtales",
      structure: "arranjo_foliar",
      value: "opostas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "myrtales",
      structure: "simetria_floral",
      value: "actinomorfa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "myrtales",
      structure: "fusao_da_corola",
      value: "dialipetala",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "myrtales",
      structure: "estrutura_marcante",
      value: "muitos_estames",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "myrtales",
      structure: "ovario",
      value: "infero",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "myrtales",
      structure: "tipo_de_fruto",
      value: "capsula_lenhosa_ou_baga_inferior",
      effect: "positive",
      weight: 5,
    },

    {
      hypothesis: "lamiales",
      structure: "arranjo_foliar",
      value: "opostas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "lamiales",
      structure: "simetria_floral",
      value: "zigomorfa",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "lamiales",
      structure: "fusao_da_corola",
      value: "gamopetala",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "lamiales",
      structure: "estrutura_marcante",
      value: "flor_bilabiada",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "lamiales",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "lamiales",
      structure: "tipo_de_fruto",
      value: "capsula_ou_baga",
      effect: "positive",
      weight: 2,
    },

    {
      hypothesis: "solanales",
      structure: "arranjo_foliar",
      value: "alternas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "solanales",
      structure: "simetria_floral",
      value: "actinomorfa",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "solanales",
      structure: "fusao_da_corola",
      value: "gamopetala",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "solanales",
      structure: "estrutura_marcante",
      value: "flor_5_mera_sem_marca_forte",
      effect: "positive",
      weight: 6,
    },
    {
      hypothesis: "solanales",
      structure: "ovario",
      value: "supero",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "solanales",
      structure: "tipo_de_fruto",
      value: "capsula_ou_baga",
      effect: "positive",
      weight: 3,
    },

    {
      hypothesis: "asterales",
      structure: "arranjo_foliar",
      value: "alternas",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "asterales",
      structure: "simetria_floral",
      value: "zigomorfa",
      effect: "positive",
      weight: 2,
    },
    {
      hypothesis: "asterales",
      structure: "fusao_da_corola",
      value: "gamopetala",
      effect: "positive",
      weight: 3,
    },
    {
      hypothesis: "asterales",
      structure: "estrutura_marcante",
      value: "anteras_concrescidas",
      effect: "positive",
      weight: 7,
    },
    {
      hypothesis: "asterales",
      structure: "ovario",
      value: "infero",
      effect: "positive",
      weight: 5,
    },
    {
      hypothesis: "asterales",
      structure: "tipo_de_fruto",
      value: "aquenio_com_papo",
      effect: "positive",
      weight: 7,
    },

    {
      hypothesis: "poales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poales",
      structure: "estrutura_marcante",
      value: "anteras_concrescidas",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poales",
      structure: "tipo_de_fruto",
      value: "legume",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "poales",
      structure: "tipo_de_fruto",
      value: "aquenio_com_papo",
      effect: "negative",
      weight: 5,
    },

    {
      hypothesis: "fabales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "fabales",
      structure: "estrutura_marcante",
      value: "anteras_concrescidas",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "fabales",
      structure: "tipo_de_fruto",
      value: "cariopse",
      effect: "negative",
      weight: 5,
    },
    {
      hypothesis: "fabales",
      structure: "ovario",
      value: "infero",
      effect: "negative",
      weight: 3,
    },

    {
      hypothesis: "myrtales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "myrtales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "myrtales",
      structure: "estrutura_marcante",
      value: "anteras_concrescidas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "myrtales",
      structure: "tipo_de_fruto",
      value: "legume",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "lamiales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiales",
      structure: "tipo_de_fruto",
      value: "legume",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "lamiales",
      structure: "tipo_de_fruto",
      value: "cariopse",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "solanales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "solanales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "solanales",
      structure: "estrutura_marcante",
      value: "anteras_concrescidas",
      effect: "negative",
      weight: 3,
    },
    {
      hypothesis: "solanales",
      structure: "ovario",
      value: "infero",
      effect: "negative",
      weight: 4,
    },

    {
      hypothesis: "asterales",
      structure: "estrutura_marcante",
      value: "espiguetas",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "asterales",
      structure: "estrutura_marcante",
      value: "flor_papilionacea",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "asterales",
      structure: "tipo_de_fruto",
      value: "legume",
      effect: "negative",
      weight: 4,
    },
    {
      hypothesis: "asterales",
      structure: "tipo_de_fruto",
      value: "cariopse",
      effect: "negative",
      weight: 4,
    },
  ],
};

export const ordensAngiospermasBrasilV1 =
  normalizeProtocol(
    rawOrdensAngiospermasBrasilV1
  );
